- name: Configure linux server
  hosts: webservers
  become: true

  tasks:
    - name: install required packages
      apt:
        name:
          - nginx
          - fail2ban
        state: present
        update_cache: true
    
    - name: deploy custom nginx page 
      copy:
        content: |
          <html>
          <body>
            <h1>Project 9: Automated Ansible configs</h1>
            <p>This server was configured automatically by ansible however im its father</p>
          <body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: create ansibleuser
      user:
        name: ansibleuser
        shell: /bin/bash
        create_home: true
        state: present

    - name: add ansibleuser to sudo group
      user:
        name: ansibleuser
        groups: sudo
        append: true

    - name: Set home directory permissions
      file:
        path: /home/ansibleuser
        owner: ansibleuser
        group: ansibleuser
        mode: '0750'