- name: Configure linux server
  hosts: webservers
  become: true

  tasks:
    - name: install required packages
      apt:
        name:
          - nginx
          - fail2ban
        state: present
        update_cache: true
    
    - name: deploy custom nginx page 
      copy:
        content: |
          <html>
          <body>
            <h1>Project 9: Automated Ansible configs</h1>
            <p>This server was configured automatically by ansible however im its father</p>
          <body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: create ansibleuser
      user:
        name: ansibleuser
        shell: /bin/bash
        create_home: true
        state: present

    - name: add ansibleuser to sudo group
      user:
        name: ansibleuser
        groups: sudo
        append: true

    - name: Set home directory permissions
      file:
        path: /home/ansibleuser
        owner: ansibleuser
        group: ansibleuser
        mode: '0750'

    - name: Deploy sysinfo script
      copy:
        content: |
          #!/bin/bash
          echo "=== System information ==="
          echo "Hostname: $(Hostname)"
          echo "Date: $(date)"
          echo "Uptime: $(uptime -p)"
          echo "Logged in users: $(who | wc -l)"
          echo ""
          echo "=== Disk usage ==="
          df -h /
          echo ""
          echo "=== Memory usage"
          free -h 
        dest: /home/ansibleuser/sysinfo.sh
        owner: ansibleuser
        group: ansibleuser 
        mode: '0755'
      
    - name: Set up cron job for sysinfo
      cron:
        name: "sysinfo collection"
        minute: "*/5"
        job: "/home/ansibleuser/sysinfo.sh >> /home/ansibleuser/sysinfo.log 2>&1"
        user: ansibleuser

    - name: Ensure nginx is enabled and running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Ensure ssh is enabled and running
      service:
        name: ssh
        state: started
        enabled: true

    - name: Disable root ssh login
      linefile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line:: 'PermitRootLogin no'
        state: present
      notify: Restart ssh

    - name: Configure fail2ban for ssh
      copy:
        content: |
         [sshd]
         enabled = true
         port = ssh
         filter = sshd
         logpath = /var/log/auth.log
         maxretry = 3
         bantime = 3600
         findtime = 600
        dest: /etc/fail2ban/jail.local
        mode: '0644'
      notify: Restart fail2ban
  
  handlers:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted

    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted